name: tests

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Run go fmt
      run: diff -u <(echo -n) <(gofmt -d -s .)

    - name: Run go vet
      run: go vet ./...

    - name: Test
      run: go test -v ./paddle
